baseURL = "https://rocktakey.netlify.app/"
languageCode = "ja"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
title = "ROCKTAKEY's Site"

pygmentsUseClasses = true
pygmentsCodefences = true

theme = "anatole"

disqusShortname = "rocktakey"

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
    tag = "tags"

[params]
    description = "Love Emacs, major medical biology, study mathematics and physics. "
    profilePicture = "images/logo.png"
    customCss = ["css/custom.css", "css/syntax.css",
    # "https://tikzjax.com/v1/fonts.css"
    ]
    customJs = ["js/custom.js", "https://tikzjax.com/v1/tikzjax.js"]
    title = "ROCKTAKEY's Site"
    author = "ROCKTAKEY"

# [params.math]
#     enable = true
#     use = "mathjax"

    mainSections = [
                 "diary",
                 "information-science",
                 "mathematics",
                 "medicine-biology",
                 "physics"
                 ]

[[params.socialIcons]]
    icon = "fa-github"
    url = "https://github.com/ROCKTAKEY"
[[params.socialIcons]]
    icon = "fa-twitter"
    url = "https://twitter.com/rocktakey"
[[params.socialIcons]]
    icon = "fa-envelope-o"
    url = "rocktakey@gmail.com"

[[params.sponsorIcons]]
    icon = "fa-amazon"
    url = "https://www.amazon.jp/hz/wishlist/ls/19PQEBYE2EL1O?ref_=wl_share"
[[params.sponsorIcons]]
    icon = "fa-heart"
    url = "https://github.com/sponsors/ROCKTAKEY"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Diary"
        url = "/Diary/"
        weight = 2
    [[menu.main]]
        name = "Information Science"
        url = "/information-science/"
        weight = 5
    [[menu.main]]
        name = "Medicine/Biology"
        url = "/medicine-biology/"
        weight = 10
    [[menu.main]]
        name = "Mathematics"
        url = "/mathematics/"
        weight = 15
    [[menu.main]]
        name = "Physics"
        url = "/physics/"
        weight = 20
    [[menu.main]]
        name = "Tags"
        url = "/tags/"
        weight = 100
